name: Auto Tag Bug Work Item

on:
  repository_dispatch:
    types: [azure-devops-bug-created]

jobs:
  tag-bug:
    runs-on: ubuntu-latest

    steps:
      - name: Add Bugs tag to work item
        run: |
          curl -X PATCH \
          -H "Content-Type: application/json-patch+json" \
          -u ":${{ secrets.AZDO_PAT }}" \
          https://dev.azure.com/abatacommerce/MyKKP/_apis/wit/workitems/${{ github.event.client_payload.workItemId }}?api-version=7.0 \
          -d '[
            {
              "op": "add",
              "path": "/fields/System.Tags",
              "value": "Bugs"
            }
          ]'
